# How to restore the CompuLab bootloader

## Download firmware according to the device dram options:
** [on the desktop PC]
[source,code]
bash <(curl -L https://raw.githubusercontent.com/compulab-yokneam/bin/refs/heads/compulab-firmware/run.me)

## Update firmware
### Prepare flashing setup
* Turn off the device.
** [for iot devices]
   Connect a USB~micto usb cable to the device programming port (micro-end) and the USB-A to a desktop PC usb port.
** [for evaluation boards]
   Connect a USB~micto usb cable to the device usb1 port (micro-end) and the USB-A to a desktop PC usb port.

* Prepare device for SDP boot.
** [for iot devices] The device gets into the SDP mode after power on if the device programming port connected to the desktop PC.
** [for evaluation boards with AltBoot button]
   Press and Hold the `AltBoot` with an empty sd-card sloot; release after power on.

* Turn on the device.
** [on the desktop PC] Make sure that the device was recognized by the ``mfgtools``:
[source,code]
sudo uuu -lsusb

### Flashing
** [on the desktop PC] Update the device bootloader using the ``mfgtools``:
[source,code]
sudo uuu -d -v -b emmc /tmp/flash.bin

### After flash verification
* Turn off the device.
* Disconnect the cable connected to the device programming port.
* Turn on the device.
* Make sure that the device is able to get to the U-boot prompt.
