#!/bin/bash

[[ -z ${IOTDIN_LIB_HOME} ]] && export IOTDIN_LIB_HOME=$(dirname $(readlink -e ${BASH_SOURCE[0]}))

# Includes
. ${IOTDIN_LIB_HOME}/common.inc
. ${IOTDIN_LIB_HOME}/gw.inc
. ${IOTDIN_LIB_HOME}/status_leds.sh

# Defines
pressed="code 171 (KEY_CONFIG), value 1"
state="ok"
cmd_button="$(readlink -e ${GW_ACCESS_CMD_BTN_HOME}/${GW_ACCESS_CMD_BTN})"
[[ -z ${cmd_button} ]] && exit 1
LEDS_HOME=${GW_ACCESS_LED_HOME}
LED_OK="green_a"
LED_SOS="red_a"

##########################################
# Switch all LEDs off
function all_leds_off() {
	for l in "${LED_OK}" "${LED_SOS}" ; do
		set_led off ${l}
	done
}

##########################################
# Cleanup and exit
##########################################
function stop_exit() {
	local ret=${1:-"0"}
	pkill -P $$
	all_leds_off
	exit ${ret}
}

##########################################
# Set a new state to a specified LED 
##########################################
function set_led() {
	local code=${1}
	local led=${2:-''}

	case ${code} in
	"off")
		echo none > ${LEDS_HOME}/${led}/trigger
		return 0
		;;
	"ok")
		led=${LED_OK}
		;;
	"sos")
		led=${LED_SOS}
		;;
	*)
		return 1
		;;
	esac

	echo "CMD Button pressed: LED state: ${led:0:-2}"
	echo pattern > ${LEDS_HOME}/${led}/trigger
	sleep 0.1
	declare -n PATTERN="PATTERN_"${code^^}
	echo "${PATTERN}" > ${LEDS_HOME}/${led}/pattern
	sleep 0.1
}


# Clear exit
trap stop_exit SIGINT

# Initial LEDs state
all_leds_off

cat << EOF
           #######################
           #   CMD Button Demo   #
           #######################

Press CMD button and observe User LED A state change

Press 'Ctrl+C' to stop the Demo
EOF

##########################################
# The main loop: 
# 1) Read input event
# 2) Detect the CMD button pressed
# 3) Set a new state (either OK or SOS)
##########################################
evtest "${cmd_button}" | while read line; do
	if [[ "${line}" == *"${pressed}"* ]] ; then
	   if [[ "${state}" == "ok" ]]; then
	   	   state="sos"
	   else
	   	   state="ok"
	   fi
	   cmd=cmd_${state}
	   command -v ${!cmd} &>/dev/null && ${cmd} || true
	fi
done
